name: build-all

on:
  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerimage:
          - alpine-ansible
          - amazon2-ansible
          - amazon2023-ansible
          - arch-ansible
          - centos7-ansible
          - centos8-ansible
          - rocky8-ansible
          - debian11-ansible
          - debian10-ansible
          - fedora37-ansible
          - fedora38-ansible
          - opensuse_tumbleweed-ansible
          - openwrt-ansible
          - oracle7-ansible
          - ubuntu1804-ansible
          - ubuntu2004-ansible
          - ubuntu2204-ansible
        platforms:
          - linux/amd64
            # #- linux/arm64
        exclude:
          - dockerimage: oracle7-ansible
            platforms: linux/arm64
          - dockerimage: arch-ansible
            platforms: linux/arm64
          - dockerimage: centos7-ansible
            platforms: linux/arm64

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerimage }}-latest
          tags: ghcr.io/nejch/docker-${{ matrix.dockerimage }}:test
          platforms: ${{ matrix.platforms }}
          load: true
      -
        name: Test
        run: |
          docker run --rm ghcr.io/nejch/docker-${{ matrix.dockerimage }}:test
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/ghcr-io'
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerimage }}-latest
          push: true
          tags: ghcr.io/nejch/docker-${{ matrix.dockerimage }}:latest
          platforms: ${{ matrix.platforms }}
        if: github.ref == 'refs/heads/ghcr-io'
